// <auto-generated />
namespace refactor_me.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EnableCascading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnableCascading));
        
        string IMigrationMetadata.Id
        {
            get { return "201805200742173_Enable-Cascading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
